CREATE TABLE concepts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    confidence INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_concepts_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT chk_concepts_confidence CHECK (confidence >= 0 AND confidence <= 100),
    CONSTRAINT chk_concepts_status CHECK (status IN (
                'NEW',
                'LEARNING',
                'UNDERSTOOD',
                'MASTERED'
            )
        ),
    CONSTRAINT uq_concepts_course_name
        UNIQUE (course_id, name)
);