CREATE TABLE concept_dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id BIGINT NOT NULL,
    prerequisite_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dependency_concept FOREIGN KEY (concept_id) REFERENCES concepts(id) ON DELETE CASCADE,
    CONSTRAINT fk_dependency_prerequisite FOREIGN KEY (prerequisite_id) REFERENCES concepts(id) ON DELETE CASCADE,
    CONSTRAINT uq_concept_prerequisite UNIQUE (concept_id, prerequisite_id),
    CONSTRAINT chk_not_self_dependency CHECK (concept_id <> prerequisite_id)
);